### ISSUE TITLE
Stratosphere.ResourceProperties.EC2SecurityGroupRule vanished in 0.4.4

### ISSUE THREAD

**Issue by MichaelXavier** [frontrowed/stratosphere#49]
Hi,

I'm upgrading packages and upgraded to stratosphere 0.4.4 and noticed the `Stratosphere.ResourceProperties.EC2SecurityGroupRule` module has vanished. Previously, the module linked to http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-security-group-rule.html which still exists and didn't show any sign of deprecation. If this was intentional, this should probably be a breaking API bump (0.5 in this case) but I suspect rather that your codegen may have quietly failed on that AWS API.

**Comment by jdreaver** [comment]
Hey @MichaelXavier! 

That property actually got split up into two properties for ingress and egress (`EC2SecurityGroupIngressProperty` and `EC2SecurityGroupEgressProperty`). I guess they are being more stringent with which properties they allow on each one. That page you link to does indeed still exist, but you can see that they have two separate schemas, one for ingress and one for egress.

I probably should have done a 0.5 bump because of the API change, sorry about that. Would a major version bump help you with your tooling somehow? I have an open PR (https://github.com/frontrowed/stratosphere/pull/48) with the next version of the specification document, and I'll be sure to give that a major version bump. I can merge that PR soon and release it.

**Comment by MichaelXavier** [comment]
@jdreaver thanks for the explanation, that make sense. Easy fix on my end. No need to make special accommodations, I've been in the same position. My solution is usually just as you propose: cut a breaking release in the next version you happen to release.
