### ISSUE TITLE
Implement conditions for resources

### ISSUE THREAD

**Issue by jdreaver** [frontrowed/stratosphere#59]
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/conditions-section-structure.html

Currently we don't have a field for `Condition` on `Resource`. Also, we should probably change the type of `templateConditions` to `Map Text (Val a)` instead of just `Object`.

**Comment by kelizarov** [comment]
Hi. I can open a PR with a fix for Condition on Resource. I'm pretty novice at haskell but I think it's not that hard with given structure of project. I already forked the project to see how it would work on our template. You can quickly check the commit here https://github.com/kelizarov/stratosphere/commit/04428b9ddb3ce386bacbb73300ca0a37a9ad7dc3

But I couldn't check if that doesnt break anything since there are not much tests.

As for `templateConditions` I think it should be done with separate PR since it would involve lots of code refactoring for existing templates.
